services:
  postgres:
    image: postgres:16.11-alpine3.23
    container_name: knowledge_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - knowledge_network

  app:
    build: .
    container_name: knowledge_api
    depends_on:
      postgres:
        condition: service_healthy 
    environment:
      DB_HOST: knowledge_db 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: "5432"
    ports:
      - "2709:2709"
    restart: unless-stopped
    networks:
      - knowledge_network

networks:
  knowledge_network:
    driver: bridge

volumes:
  postgres_data:
    name: knowledge_data