services:
  postgres:
    image: postgres
    container_name: knowledge_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - knowledge_data:/var/lib/postgresql/
    restart: unless-stopped

volumes:
  knowledge_data:
